# Site settings
title: Moon-sky
header-img: "img/tree.jpg"
tagline: "吉光片羽"  
description: "我本一过客，天地长悠悠"  
baseurl: ""
url: "http://moon-sky.github.io"  
#url: "http://localhost:4000"

# About/contact
owner: 
  name: "Moon-sky"
  email: wanghexinmail@gmail.com
  bio: "我本一过客，天地长悠悠"

# Data
gavatar: https://avatars0.githubusercontent.com/u/4860088?v=3&u=ad02bccd9bc83d0f226e5fa012f6f79b30c67058&s=140
favicon: img/favicon.ico
 
github_username: Moon-sky  
 

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems: 
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Moon-sky"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : moon-sky
  disqus :
      short_name : moon-sky

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
ju